### PR TITLE
Add another 654F version

### PR DESCRIPTION
**Pull request by nirvananils**

### CODE REVIEW

**Comment by Mr-MIBonk** [comment]
thank's Nils!

**Comment by ShadoViX** [comment]
Sorry but I can't write anywhere so I'll write here.
In parameter S the lane assist time is written as IEEE-745: 0x00,0x80,0xBB,0x44
And the activation speed is probably also IEEE-745.
In parameters R and S the activation is from 60km\h: 0x00,0x00,0x70,0x42 and in parameters M from 65km\h: 0x00,0x00,0x82,0x42

**Comment by ShadoViX** [comment]
Sorry but I can't write anywhere so I'll write here.
In parameter S the lane assist time is written as the inverse of IEEE-745: 0x00,0x80,0xBB,0x44
And the activation speed is probably also written as the inverse of IEEE-745.
In parameters R and S the activation is from 60km\h: 0x00,0x00,0x70,0x42 and in parameters M from 65km\h: 0x00,0x00,0x82,0x42

**Comment by nirvananils** [comment]
Did you test these findings?
As this one I found weeks ago, but not working for me:
M from 65km\h: 0x00,0x00,0x82,0x42

**Comment by ShadoViX** [comment]
I tested the lane assist time and it works. And I don't know about the activation speed, whether it has additional safeguards or is written differently, and my thoughts are wrong. I compared and tested M, R and S. In M 65 km\h is activated, and in R and S from 60 km\h. I didn't test the P parameter, but it is written 0x00,0x00,0x70,0x42, so from the theory it would follow that the activation is also from 60 km\h

**Comment by ShadoViX** [comment]
S-parameter Tiguan made for 300s.
https://dropmefiles.com/OuH1t

**Comment by nirvananils** [comment]
Okay let me investigate later if iam back at home.
could you maybe write the offset for M and S? As there are different offset with same value

**Comment by ShadoViX** [comment]
Here you have an R file for 300s and the M offset is the same as R.
https://dropmefiles.com/5iybQ

**Comment by dmitrijsmihailovs** [comment]
Hi, guys. 
Any progress on M/S? I will later get M camera (still looking for dataset). Would be able to test if needed.

**Comment by ShadoViX** [comment]
I also have them for M and S. But M is not publicly available and the friend I got them from has forbidden sharing.

**Comment by dmitrijsmihailovs** [comment]
> I also have them for M and S. But M is not publicly available and the friend I got them from has forbidden sharing.

Camera is on the way, but I got M dataset already.
As I understand, you have figured out how to change time, but what about activation speed?

**Comment by ShadoViX** [comment]
The time of driving on the track is confirmed. As for activation, theoretically between the parameters in which there is activation from 60 km\h and 65 km\h you can observe data that would correspond to the activation speed, but I do not have a camera for testing.

**Comment by dmitrijsmihailovs** [comment]
> The time of driving on the track is confirmed. As for activation, theoretically between the parameters in which there is activation from 60 km\h and 65 km\h you can observe data that would correspond to the activation speed, but I do not have a camera for testing.

I can probably test this weekend.
As I am new to this thing, I don't really know what exactly to look for in the dataset and how to change it.
I guess if we know where time and speed is, we could probably create a new set using the config calculator tool in this repo?
It could then make necessary changes and I could test it.

**Comment by ShadoViX** [comment]
It's not that simple. Time I know where to change but as for speed I tested and the parameter didn't pass. Either it's not the data or there is some additional checksum.

**Comment by dmitrijsmihailovs** [comment]
@ShadoViX Hello, so I got the camera and put it in the car.
Would you then be able to share how to change the time in the dataset?

**Comment by ShadoViX** [comment]
@dmitrijsmihailovs Write to me on Drive2

**Comment by ShadoViX** [comment]
> @ShadoViX Hello, so I got the camera and put it in the car. Would you then be able to share how to change the time in the dataset?

Write to me on Drive2

**Pull request merged**
